name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OPMLPATH: output/technet.opml

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.8

#    - name: Build
#      run: go build -v ./...

#    - name: Test
#      run: go test -v ./...

    - name: Run
      run: go run ./main.go

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Commit generated OPML
